# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-12 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210512_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(default='', max_length=200),
        ),
    ]
